export default `
  type User {
    _id: ID!
    email: String!
    username: String!
    password: String!
    createdAt: String!
    updatedAt: String!
  }

  type Query {
    Users: [User!]
    User(_id: ID!): User
  }

  type Mutation {
    createUser(email: String!, username: String!, password: String!): User!
  }
`